"""Shared error-card context builders for dashboard HTML responses."""

from __future__ import annotations

from typing import Any

from arguss.core.models import LensFailureSkip
from arguss.core.parser import ParserError
from arguss.engine.propose import ProposalReport


def is_unsupported_lockfile_error(exc: ParserError) -> bool:
    msg = str(exc).lower()
    return "lockfileversion" in msg or "is not supported" in msg


def unsupported_lockfile_card_context() -> dict[str, Any]:
    return {
        "error_title": "Couldn't read this lockfile",
        "error_message": (
            "Arguss supports lockfileVersion 2 and 3 "
            "(generated by npm 7 and newer). "
            "Your lockfile uses an older format."
        ),
        "error_suggestions": [
            "Make sure you have npm 7 or newer: <code>npm --version</code>",
            "Delete the existing <code>package-lock.json</code>",
            "Run <code>npm install</code> to regenerate the lockfile",
            "Upload the new <code>package-lock.json</code>",
        ],
        "error_action": {
            "label": "Try Scan instead",
            "url": "/scan",
            "kind": "primary",
        },
        "error_secondary_action": {
            "label": "Back to Upload",
            "url": "/upload",
        },
        "error_kind": "lockfile",
    }


def lockfile_parse_card_context() -> dict[str, Any]:
    return {
        "error_title": "Couldn't read this lockfile",
        "error_message": "The uploaded file didn't parse as a valid package-lock.json.",
        "error_suggestions": [
            "Confirm the file is the <code>package-lock.json</code> from your project root",
            "Make sure the file isn't truncated or corrupted",
        ],
        "error_action": {"label": "Back to Upload", "url": "/upload", "kind": "primary"},
        "error_kind": "upload",
    }


def parser_error_card_context(exc: ParserError) -> dict[str, Any]:
    if is_unsupported_lockfile_error(exc):
        return unsupported_lockfile_card_context()
    ctx = lockfile_parse_card_context()
    ctx["error_message"] = str(exc)
    return ctx


def network_error_card_context(
    *,
    title: str,
    message: str,
    suggestions: list[str] | None = None,
    action_url: str = "/scan",
    action_label: str = "Back to Scan",
    secondary_action: dict[str, str] | None = None,
) -> dict[str, Any]:
    ctx: dict[str, Any] = {
        "error_title": title,
        "error_message": message,
        "error_suggestions": suggestions or [],
        "error_action": {"label": action_label, "url": action_url, "kind": "primary"},
        "error_kind": "network",
    }
    if secondary_action:
        ctx["error_secondary_action"] = secondary_action
    return ctx


def scan_rate_limited_card_context(message: str) -> dict[str, Any]:
    """Legible card for a scan-frequency limit hit (browser/HTMX flows)."""
    return network_error_card_context(
        title="Scan limit reached",
        message=message,
        suggestions=[
            "Wait a while before starting another scan",
            "Revisit an existing assessment, viewing cached results is not limited",
        ],
    )


def request_rate_limited_card_context(message: str) -> dict[str, Any]:
    """Legible card for the general per-IP request backstop (browser/HTMX)."""
    return network_error_card_context(
        title="Too many requests",
        message=message,
        suggestions=["Wait a moment and try again"],
    )


def github_fetch_error_card_context(message: str) -> dict[str, Any]:
    return network_error_card_context(
        title="Couldn't fetch repository",
        message=message,
        suggestions=[
            "Check the URL spelling and that the repository is public",
            "Confirm the branch or tag exists",
            "Try Upload if the repo is private or not on GitHub",
        ],
        secondary_action={"label": "Try Upload instead", "url": "/upload"},
    )


def git_clone_error_card_context(*, timed_out: bool) -> dict[str, Any]:
    if timed_out:
        return network_error_card_context(
            title="Repository clone timed out",
            message="Clone took too long; the repository may be too large.",
            suggestions=[
                "Try a smaller repository or a shallow clone from the command line",
                "Use Upload with a local package-lock.json instead",
            ],
            secondary_action={"label": "Try Upload instead", "url": "/upload"},
        )
    return network_error_card_context(
        title="Repository not found",
        message="Repository not found or not accessible.",
        suggestions=[
            "Check the URL spelling and repository visibility",
            "For private repos, use Upload, or connect the arguss-bot GitHub App when opening PRs",
        ],
        secondary_action={"label": "Try Upload instead", "url": "/upload"},
    )


def upload_zip_error_card_context(message: str) -> dict[str, Any]:
    return {
        "error_title": "Couldn't process upload",
        "error_message": message,
        "error_suggestions": [
            "Zip only your <code>.github/workflows/</code> directory contents",
            "Use <code>.yml</code> or <code>.yaml</code> workflow files",
            "Re-upload <code>package-lock.json</code> if the lockfile was invalid",
        ],
        "error_action": {"label": "Back to Upload", "url": "/upload", "kind": "primary"},
        "error_kind": "upload",
    }


def osv_unavailable_card_context() -> dict[str, Any]:
    return network_error_card_context(
        title="Vulnerability data unavailable",
        message="OSV.dev could not be reached. Arguss could not query known CVEs.",
        suggestions=[
            "Check your network connection and try again in a few minutes",
            "Confirm <code>OSV_API_BASE</code> points to a reachable OSV API if customized",
        ],
        action_label="Retry scan",
        action_url="/scan",
    )


_AUTH_FAILURE_MARKERS = (
    "github app authorization failed",
    "does not have access to this repository",
)

# Matches the classified detail for the GitHub App not-installed 403
# (see APP_NOT_INSTALLED_DETAIL in arguss.web.github_action).
_APP_NOT_INSTALLED_MARKER = "isn't installed on this repository"


def _remediation_failure_suggestions(message: str) -> list[str]:
    lower = message.lower()
    if _APP_NOT_INSTALLED_MARKER in lower:
        return [
            "If you don't own this repository, fork it and scan your fork",
            (
                "Otherwise, install arguss-bot on this repository "
                "(or check its repository access) and retry"
            ),
        ]
    if any(marker in lower for marker in _AUTH_FAILURE_MARKERS):
        return [
            "Check that arguss-bot is still installed on this repository",
            "Ensure the App's repository access includes Contents and Pull requests",
            "Reconnect arguss-bot from the authorize step and retry",
        ]
    if "rate limit" in lower:
        return [
            "Wait until the reset time shown above, then try again",
            "Return to authorize once the limit resets",
        ]
    if message.strip():
        # A concrete reason is displayed on the card; there is no phantom
        # "message above" to point at.
        return ["Return to authorize to try again"]
    return [
        "Review the message above for the specific cause",
        "Return to authorize to try again",
    ]


def _remediation_failure_kind(message: str) -> str:
    lower = message.lower()
    if (
        any(marker in lower for marker in _AUTH_FAILURE_MARKERS)
        or _APP_NOT_INSTALLED_MARKER in lower
        or "rate limit" in lower
    ):
        return "network"
    return "generic"


def wizard_remediation_failed_card_context(
    *,
    scan_hash: str,
    message: str = "",
) -> dict[str, Any]:
    """Error card shell for wizard process-page remediation failures (SSE-filled message)."""
    return {
        "error_title": "Remediation failed",
        "error_message": message,
        "error_suggestions": _remediation_failure_suggestions(message),
        "error_action": {
            "label": "← Back to authorize",
            "url": "/authorize",
            "kind": "primary",
        },
        "error_secondary_action": {
            "label": "Back to assessment",
            "url": f"/assessment/{scan_hash}",
        },
        "error_kind": _remediation_failure_kind(message),
    }


def generic_error_card_context(
    message: str = "Something went wrong during the scan. Please try again.",
) -> dict[str, Any]:
    return {
        "error_title": "Scan failed",
        "error_message": message,
        "error_suggestions": ["Wait a moment and run the scan again"],
        "error_action": {
            "label": "Refresh",
            "url": "javascript:location.reload()",
            "kind": "primary",
        },
        "error_kind": "generic",
    }


def report_has_osv_unavailable(report: ProposalReport) -> bool:
    for item in report.skipped_findings:
        if isinstance(item, LensFailureSkip) and item.reason == "osv_unavailable":
            return True
    return False
