"""Chat assistant rename: Arguss sender label + Arguss Assistant prompt identity.

The chat is an explanation layer over Arguss's deterministic engine. The
display name and self-identity are Arguss-branded; the honest "built on
Claude / Anthropic" attribution elsewhere must remain untouched.
"""

from __future__ import annotations

from pathlib import Path
from unittest import mock

from fastapi import status
from fastapi.testclient import TestClient

from arguss.api import create_app
from arguss.explanations.chat import _SYSTEM_PROMPT_TEMPLATE

_TEMPLATES = Path("arguss/web/templates")
_CHAT_TURN = _TEMPLATES / "partials" / "_chat_turn.html"
_CHAT_PANEL = _TEMPLATES / "partials" / "_chat_panel.html"


# --- UI sender label ---


def test_chat_turn_partial_sender_is_arguss_not_claude() -> None:
    html = _CHAT_TURN.read_text()
    assert '<span class="chat-message-sender">Arguss</span>' in html
    assert "Claude" not in html


def test_typing_indicator_sender_is_arguss_not_claude() -> None:
    html = _CHAT_PANEL.read_text()
    assert '<span class="chat-message-sender">Arguss</span>' in html
    assert "Claude" not in html


def test_rendered_chat_turn_attributes_answer_to_arguss() -> None:
    client = TestClient(create_app())
    scan = {
        "entries": [],
        "skipped_findings": [],
        "summary": {},
        "project_scores": {},
        "executive_summary": None,
    }
    with (
        mock.patch(
            "arguss.explanations.chat.get_cached_scan_response",
            return_value=scan,
        ),
        mock.patch(
            "arguss.explanations.chat.call_claude",
            return_value="Test answer.",
        ),
    ):
        response = client.post(
            "/dashboard/chat",
            data={
                "scan_input_hash": "abc123",
                "history_json": "[]",
                "question": "What should I review first?",
            },
        )

    assert response.status_code == status.HTTP_200_OK
    assert '<span class="chat-message-sender">Arguss</span>' in response.text
    assert "Claude" not in response.text


# --- system prompt identity + layering ---


def test_prompt_identifies_as_arguss_assistant() -> None:
    assert "Arguss Assistant" in _SYSTEM_PROMPT_TEMPLATE
    assert "explanation assistant for Arguss" in _SYSTEM_PROMPT_TEMPLATE


def test_prompt_states_it_does_not_make_verdicts() -> None:
    prompt = _SYSTEM_PROMPT_TEMPLATE
    assert "deterministic engine" in prompt
    assert "do not make, change, or influence verdicts" in prompt
    # Must not imply the AI produced the tier decision.
    assert "not by you" in prompt


def test_prompt_instructs_against_self_identifying_as_claude() -> None:
    assert "Do not self-identify as Claude" in _SYSTEM_PROMPT_TEMPLATE


def test_prompt_keeps_architecture_overview_and_glossary() -> None:
    prompt = _SYSTEM_PROMPT_TEMPLATE.lower()
    assert "zizmor" in prompt
    assert "pipeline" in prompt
    assert "terminology mapping" in prompt
    assert "veto" in prompt


# --- guard: honest Claude/Anthropic attribution untouched ---


def test_exec_summary_chip_still_credits_claude() -> None:
    html = (_TEMPLATES / "partials" / "_exec_summary.html").read_text()
    assert "Generated by Claude" in html


def test_stack_attribution_pages_still_mention_claude_api() -> None:
    assert "Anthropic Claude API" in (_TEMPLATES / "about.html").read_text()
    assert "Claude API" in (_TEMPLATES / "how_it_works.html").read_text()


def test_anthropic_client_module_untouched_by_rename() -> None:
    source = Path("arguss/explanations/_client.py").read_text()
    assert "def call_claude(" in source
    assert "Call Claude with the given prompts" in source
